services:
  - type: web
    name: pumpfun-api-bundler
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      # Add more environment variables here if needed, e.g.:
      # - key: SOME_SECRET
      #   value: your_secret_value 